// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
//=require "main"
//=require "counterup/counterup.min"
//=require "easing/easing"
//=require "easing/easing.min"
//=require "owlcarousel/owl.carousel"
//=require "owlcarousel/owl.carousel.min"
//=require "tempusdominus/moment-timezone.min"
//=require "tempusdominus/moment.min"
//=require "tempusdominus/tempusdominus-bootstrap-4"
//=require "tempusdominus/tempusdominus-bootstrap-4.min"
//=require "waypoints/waypoints.min"
//=require "wow/wow.js"
//=require "wow/wow.min.js"
